site_name: Q-Twin Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [srcs] 

nav:
  - Home: index.md
  - Installation & Setup: installation.md
  - API Reference: api.md
