site_name: Q-Twin Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [srcs] 
          options:
            show_root_heading: true       # Displays the module name as a header
            show_source: true             # Adds collapsible source code dropdowns
            heading_level: 2              # Keeps sub-functions under H2/H3
            members_order: source         # Keeps the same order as in your .py file
            separate_signature: true      # Puts function parameters on clean new lines

nav:
  - Home: index.md
  - Installation & Setup: installation.md
  - Usage Procedure & Example: workflow.md
  - API Reference: api.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."]      
      check_paths: true     
  - pymdownx.superfences